Update catholic-order.ttl
nie-ine/Ontologies pull request #13
Opened 2020-10-15 12:20 UTC by rebplu

2020-10-19 08:27 UTC, hanscools approved these changes

2020-10-21 07:34 UTC, hanscools approved these changes

2020-10-21 22:01 UTC, hanscools approved these changes

2020-10-21 22:01 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/catholic-order.ttl
> +	rdfs:label "friar role"@en, "Ordensbruder"@de;
TBD

2020-10-21 22:42 UTC, hanscools approved these changes

2020-10-21 22:42 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/creating.ttl
> +	rdfs:label "creating"@en, "erstellen"@de;
TBD

2020-10-21 22:42 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/creating.ttl
> +	rdfs:comment """Group of person's creation."""@en;
TBD

2020-10-21 22:42 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/creating.ttl
> +	rdfs:comment """Set of person's creations."""@en;
TBD

2020-10-21 22:42 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/device.ttl
> +	rdfs:comment """Computer using digital software and data to perform a task."""@en;
TBD

2020-10-21 22:42 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/document.ttl
> +	rdfs:subClassOf document:BibliographicReference.
TBD

2020-10-21 22:43 UTC, hanscools approved these changes

2020-10-21 22:44 UTC, hanscools approved these changes

2020-10-21 22:45 UTC, hanscools approved these changes

2020-10-21 22:45 UTC, hanscools approved these changes

2020-10-21 22:45 UTC, hanscools approved these changes

2020-10-21 22:46 UTC, hanscools approved these changes

2020-10-24 23:54 UTC, hanscools approved these changes

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/event.ttl
> +	rdfs:subClassOf event:Process.
TBD

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Political organization of a nation with an own government."""@en;
Comment to be adapted.

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Political organization of a nation with an own government."""@en;
Comment to be adapted.

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Exercises authority over a particular territory."""@en.
TBD

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Role of a man being the absolute ruler in a monarchy."""@en;
TBD

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Role of a woman being the absolute ruler in a monarchy."""@en;
TBD

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Role of a man being a sovereign head of an empire."""@en;
TBD

2020-10-24 23:54 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Role of a woman being a sovereign head of an empire."""@en;
TBD

2020-10-24 23:55 UTC, hanscools approved these changes

2020-10-24 23:55 UTC, hanscools approved these changes

2020-10-24 23:57 UTC, hanscools approved these changes

2020-10-24 23:57 UTC, hanscools approved these changes

2020-10-24 23:58 UTC, hanscools approved these changes

2020-10-24 23:58 UTC, hanscools approved these changes

2020-10-25 00:27 UTC, hanscools approved these changes

2020-10-25 00:41 UTC, hanscools requested changes

2020-10-25 00:41 UTC, hanscools commented on Nie-ontologies/Generic-ontologies/human-geography.ttl
> +	rdfs:comment """Group of politicians which exercise authority over a particular territory."""@en.
"One or more persons in a politician role exercising authority over a particular territory."

2020-10-25 07:16 UTC, rebplu commented
I resolved all comments from yesterday, because these commits were all outdated and I solved it already (see commits from last thursday). Here the overview of all changes which at this stage are made with this pull request: 
[https://github.com/nie-ine/Ontologies/pull/13/files#diff-0a06259006bdf511ea7c7e3d663a48afd619381c508f7f1a0c25b9c41cb9203f](https://github.com/nie-ine/Ontologies/pull/13/files#diff-0a06259006bdf511ea7c7e3d663a48afd619381c508f7f1a0c25b9c41cb9203f)

If everything is ok, could you merge untill tomorrow, so that I can move on?

2020-10-25 20:48 UTC, hanscools approved these changes

2020-10-25 20:53 UTC, merged